import { render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { beforeEach, describe, expect, it, vi } from 'vitest';

import ProgressNoteForm from '../ProgressNoteForm';

const { submitMock } = vi.hoisted(() => ({
  submitMock: vi.fn(),
}));

vi.mock('@/hooks/useUserTimezone', () => ({
  useUserTimezone: () => 'America/New_York',
}));

vi.mock('@/utils/date/timezoneUtils', () => ({
  getCurrentDateInUserTimezone: () => '2026-04-24',
  parseDateOnlyAsLocalDate: (value: string) => {
    const match = value.match(/^(\d{4})-(\d{2})-(\d{2})$/);
    if (!match) return null;
    return new Date(Number(match[1]), Number(match[2]) - 1, Number(match[3]));
  },
}));

vi.mock('@/hooks/useProgressImageCompression', () => ({
  useProgressImageCompression: () => ({
    compressImage: vi.fn(),
    isCompressing: false,
    compressionProgress: null,
    resetCompressionState: vi.fn(),
  }),
}));

vi.mock('@/components/notes/RichTextEditor.lazy', () => ({
  default: ({
    value,
    onChange,
    disabled,
  }: {
    value: string;
    onChange: (value: string) => void;
    disabled?: boolean;
  }) => (
    <textarea
      aria-label="Progress note content"
      value={value}
      disabled={disabled}
      onChange={event => onChange(event.target.value)}
    />
  ),
}));

describe('ProgressNoteForm rich text', () => {
  beforeEach(() => {
    submitMock.mockReset().mockResolvedValue(undefined);
  });

  it('submits Markdown generated by the editor', async () => {
    const user = userEvent.setup();

    render(<ProgressNoteForm onSubmit={submitMock} />);

    await user.type(screen.getByLabelText('Progress note content'), '**Finished the border**');
    await user.click(screen.getByRole('button', { name: 'Add Note' }));

    await waitFor(() => {
      expect(submitMock).toHaveBeenCalledWith({
        date: '2026-04-24',
        content: '**Finished the border**',
        imageFile: undefined,
      });
    });
  });

  it('allows image-only progress notes with empty content', async () => {
    const user = userEvent.setup();

    render(<ProgressNoteForm onSubmit={submitMock} />);

    await user.click(screen.getByRole('button', { name: 'Add Note' }));

    await waitFor(() => {
      expect(submitMock).toHaveBeenCalledWith({
        date: '2026-04-24',
        content: '',
        imageFile: undefined,
      });
    });
  });

  it('renders a dedicated footer submit action for dialog sheets without sticky positioning', () => {
    render(<ProgressNoteForm onSubmit={submitMock} variant="dialog-sheet" />);

    const buttonWrapper = screen.getByRole('button', { name: 'Add Note' }).parentElement;
    expect(buttonWrapper).toHaveClass('shrink-0');
    expect(buttonWrapper).toHaveClass('border-t');
    expect(buttonWrapper).not.toHaveClass('sticky');
    expect(buttonWrapper).not.toHaveClass('bottom-0');
  });
});
