/// <reference path="../pb_data/types.d.ts" />
migrate(
  app => {
    const collection = new Collection({
      createRule: null,
      deleteRule: null,
      fields: [
        {
          autogeneratePattern: '[a-z0-9]{15}',
          help: '',
          hidden: false,
          id: 'text3208210256',
          max: 15,
          min: 15,
          name: 'id',
          pattern: '^[a-z0-9]+$',
          presentable: false,
          primaryKey: true,
          required: true,
          system: true,
          type: 'text',
        },
        {
          cascadeDelete: true,
          collectionId: 'pbc_2820000004',
          help: '',
          hidden: false,
          id: 'relation336246304',
          maxSelect: 1,
          minSelect: 0,
          name: 'page',
          presentable: false,
          required: true,
          system: false,
          type: 'relation',
        },
        {
          cascadeDelete: true,
          collectionId: '_pb_users_auth_',
          help: '',
          hidden: false,
          id: 'relation2375276105',
          maxSelect: 1,
          minSelect: 0,
          name: 'user',
          presentable: false,
          required: true,
          system: false,
          type: 'relation',
        },
        {
          help: '',
          hidden: false,
          id: 'file142008537',
          maxSelect: 100,
          maxSize: 52428800,
          mimeTypes: ['image/jpeg', 'image/png', 'image/webp', 'image/gif'],
          name: 'photos',
          presentable: false,
          protected: true,
          required: false,
          system: false,
          thumbs: ['320x320f'],
          type: 'file',
        },
        {
          autogeneratePattern: '',
          help: '',
          hidden: false,
          id: 'text18589324',
          max: 100000,
          min: 0,
          name: 'notes',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text',
        },
        {
          hidden: false,
          id: 'autodate2990389176',
          name: 'created',
          onCreate: true,
          onUpdate: false,
          presentable: false,
          system: false,
          type: 'autodate',
        },
        {
          hidden: false,
          id: 'autodate3332085495',
          name: 'updated',
          onCreate: true,
          onUpdate: true,
          presentable: false,
          system: false,
          type: 'autodate',
        },
      ],
      id: 'pbc_4211420130',
      indexes: [
        'CREATE UNIQUE INDEX idx_color_reference_page ON coloring_page_color_references (page)',
      ],
      listRule:
        '@request.auth.id != "" && user = @request.auth.id && page.book.user = @request.auth.id',
      name: 'coloring_page_color_references',
      system: false,
      type: 'base',
      updateRule: null,
      viewRule:
        '@request.auth.id != "" && user = @request.auth.id && page.book.user = @request.auth.id',
    });

    return app.save(collection);
  },
  () => {
    throw new Error('Refusing destructive rollback: color references contain saved user work.');
  }
);
