/// <reference path="../pb_data/types.d.ts" />
migrate(
  app => {
    const collection = new Collection({
      createRule: null,
      deleteRule: null,
      fields: [
        {
          autogeneratePattern: '[a-z0-9]{15}',
          help: '',
          hidden: false,
          id: 'text3208210256',
          max: 15,
          min: 15,
          name: 'id',
          pattern: '^[a-z0-9]+$',
          presentable: false,
          primaryKey: true,
          required: true,
          system: true,
          type: 'text',
        },
        {
          cascadeDelete: true,
          collectionId: '_pb_users_auth_',
          help: '',
          hidden: false,
          id: 'relation2375276105',
          maxSelect: 1,
          minSelect: 0,
          name: 'user',
          presentable: false,
          required: true,
          system: false,
          type: 'relation',
        },
        {
          help: '',
          hidden: false,
          id: 'select1204587666',
          maxSelect: 1,
          name: 'action',
          presentable: false,
          required: true,
          system: false,
          type: 'select',
          values: ['link', 'unlink'],
        },
        {
          help: '',
          hidden: false,
          id: 'select1215276021',
          maxSelect: 1,
          name: 'target_provider',
          presentable: false,
          required: true,
          system: false,
          type: 'select',
          values: ['apple', 'google', 'discord'],
        },
        {
          help: '',
          hidden: false,
          id: 'select900501557',
          maxSelect: 1,
          name: 'verification_method',
          presentable: false,
          required: true,
          system: false,
          type: 'select',
          values: ['password', 'oauth'],
        },
        {
          help: '',
          hidden: false,
          id: 'select1661729678',
          maxSelect: 1,
          name: 'verification_provider',
          presentable: false,
          required: false,
          system: false,
          type: 'select',
          values: ['apple', 'google', 'discord'],
        },
        {
          autogeneratePattern: '',
          help: '',
          hidden: false,
          id: 'text4197249163',
          max: 64,
          min: 0,
          name: 'verification_identity_hash',
          pattern: '^[a-f0-9]{64}$',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text',
        },
        {
          autogeneratePattern: '',
          help: '',
          hidden: false,
          id: 'text733053279',
          max: 64,
          min: 0,
          name: 'proof_hash',
          pattern: '^[a-f0-9]{64}$',
          presentable: false,
          primaryKey: false,
          required: true,
          system: false,
          type: 'text',
        },
        {
          help: '',
          hidden: false,
          id: 'date2593941644',
          max: '',
          min: '',
          name: 'expires',
          presentable: false,
          required: true,
          system: false,
          type: 'date',
        },
      ],
      id: 'pbc_4154294146',
      indexes: [
        'CREATE UNIQUE INDEX idx_auth_step_up_proof_hash ON auth_step_up_proofs (proof_hash)',
        'CREATE UNIQUE INDEX idx_auth_step_up_proof_scope ON auth_step_up_proofs (user, action, target_provider)',
        'CREATE INDEX idx_auth_step_up_proof_expiry ON auth_step_up_proofs (expires)',
      ],
      listRule: null,
      name: 'auth_step_up_proofs',
      system: false,
      type: 'base',
      updateRule: null,
      viewRule: null,
    });

    return app.save(collection);
  },
  () => {
    throw new Error('Refusing destructive rollback: step-up proofs may be active.');
  }
);
